###################################################
# Stage: base
# 
# This base stage ensures all other stages are using the same base image
# and provides common configuration for all stages, such as the working dir.
###################################################
FROM node:20 AS base
USER node
WORKDIR /home/node/local/app

################## CLIENT STAGES ##################

###################################################
# Stage: client-base
#
# This stage is used as the base for the client-dev and client-build stages,
# since there are common steps needed for each.
###################################################
FROM base AS client-base
COPY client/package.json client/yarn.lock ./
USER root
RUN  yarn install
USER node
COPY client/.eslintrc.cjs client/index.html client/vite.config.js ./
COPY client/public ./public
COPY client/src ./src

###################################################
# Stage: client-dev
# 
# This stage is used for development of the client application. It sets 
# the default command to start the Vite development server.
###################################################
FROM client-base AS client-dev
USER node
CMD ["yarn", "dev"]

###################################################
# Stage: client-build
#
# This stage builds the client application, producing static HTML, CSS, and
# JS files that can be served by the backend.
###################################################
FROM client-base AS client-build
USER node
RUN yarn build




###################################################
################  BACKEND STAGES  #################
###################################################

###################################################
# Stage: backend-base
#
# This stage is used as the base for the backend-dev and test stages, since
# there are common steps needed for each.
###################################################
FROM base AS backend-dev
USER node
COPY backend/package.json backend/yarn.lock ./
USER root
RUN yarn install --frozen-lockfile
USER node
COPY backend/spec ./spec
COPY backend/src ./src
CMD ["yarn", "dev"]

###################################################
# Stage: test
#
# This stage runs the tests on the backend. This is split into a separate
# stage to allow the final image to not have the test dependencies or test
# cases.
###################################################
FROM backend-dev AS test
RUN yarn test

###################################################
# Stage: final
#
# This stage is intended to be the final "production" image. It sets up the
# backend and copies the built client application from the client-build stage.
#
# It pulls the package.json and yarn.lock from the test stage to ensure that
# the tests run (without this, the test stage would simply be skipped).
###################################################
FROM base AS final
USER node
ENV NODE_ENV=production
COPY --from=test /home/node/local/app/package.json ./
USER root
RUN yarn install --production
RUN mkdir /home/node/todos && chmod -R 775 /home/node/todos
USER node
COPY backend/src ./src
COPY --from=client-build /home/node/local/app/dist ./src/static
EXPOSE 3000
CMD ["node", "src/index.js"]